### ISSUE TITLE
ON ATTEND LA VERSION REACT POUR PUBLIER QUOI QUE CE SOIT

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.fr#352]
# roadmap react reboot

note: chaque tache ci dessous à peut-être des choses intéressantes liés dans `./todo`.
Ce dossier devra être vide pour les bonnes raisons avant publish de cette nouvelle version. Je pense qu'on se comprends :)

- [ ] convertir les posts au format souhaité [@MoOx]
- [x] parsing des .md
- [ ] pre-render des pages
  - [x] post
  - [ ] home
  - [ ] liste
  - [ ] page spécifique
- [x] base du routing (:warning: en attente du support 0.13 de react-router)
- [x] logique de fetching de la data côté front
- [x] récupération de la data initiale côté front
- [ ] séparation correcte des CSS
- [ ] pre-render pour `style-loader/usable`
- [ ] update cssrecipes
- [ ] intégration des contributeurs
  - [ ] authors json
  - [ ] task contribution + cache
  - [ ] contributeur de chaque pages sur chaque pages
- [ ] server-side rendering ?
- [ ] eslint
- [ ] travis testing
- [ ] feed.xml
- [ ] sitemap.xml ?
- [ ] commentaires (disqus, on traitera la migration après)
- [ ] script deploy
- [ ] listes des posts 
- [ ] home
  - [ ] liste des derniers posts
  - [ ] manifesto
  - [ ] top contributeur
- [ ] 404
- [ ] Vérifier tracker analytics
- [ ] CNAME
- [ ] favicon (automatiser le build du favicon pour toute plateforme)
- [ ] redirection des posts à url pourri (post/entreprendre/*)
- [ ] Revoir CONTRIBUTING.md et le post sur comment contribuer (merger tout ça c'est pénible à maintenir 2 ressources)
- [ ] Revoir README.md + README branche buildé
- [ ] vérifier que `./todo` est vide (rien ne devrait rester)
- [ ] trouver un hébergeur node gratos si nécessaire (eg: render static trop compliqué) (heroku?)
- [ ] travis deploy

--

# le format des posts
```
---
title: Flux, qu'est-ce que c'est ?
route: post/js/flux-qu-est-ce-que-c-est
comments: true
authors:
  - bloodyowl
tags:
  - javascript
  - reactjs
  - flux
date: 2014-10-27
---

# markdown
```

**Comment by MoOx** [comment]
@bloodyowl j'ai mis n'importe quoi un peu, mais c'est pour te mettre la pression :)
Libre à toi d'update cette issue ;)

**Comment by lionelB** [comment]
c'est bizarre je vois pas la branche react. c'est un bug dans github ?

**Comment by MoOx** [comment]
Cet enculé de @bloodyowl se la garde en secret... :(

**Comment by bloodyowl** [comment]
**current status**

- [ ] conversion de tous les .md au nouveau format
- [x] parsing des .md
- [ ] pre-render des pages
  - [x] post
  - [ ] home
  - [ ] liste
  - [ ] page spécifique
- [x] base du routing (:warning: en attente du support 0.13 de react-router)
- [x] logique de fetching de la data côté front
- [x] récupération de la data initiale côté front
- [ ] update cssrecipes
- [ ] séparation correcte des CSS
- [ ] pre-render pour `style-loader/usable`

**Comment by MoOx** [comment]
Bon à savoir.
Tu la pousses quand la branche qu'on avance dessus en équipe ? :)

**Comment by magsout** [comment]
![push](https://cloud.githubusercontent.com/assets/1997108/6634209/dffb520a-c954-11e4-932e-8ab36fee8d57.gif)

**Comment by madx** [comment]
![](http://gifrific.com/wp-content/uploads/2015/01/Cat-Falling-Asleep.gif)

**Comment by MoOx** [comment]
j'ai update la desc à partir de https://gist.github.com/bloodyowl/4c88983b6643eb957905

**Comment by MoOx** [comment]
j'ai mis des noms à côté des tasks, on peut en voir ça ici si vous voulez.

**Comment by bloodyowl** [comment]
pour le server-side, je pense à :
- utiliser level pour stocker les posts & auteurs
- update uniquement le nécessaire dans la database à chaque deploy

du coup ce serait ultra facile de générer le JSON dynamiquement pour les tris par tags et autres features auxquels on pourrait penser. 

vous en pensez quoi?

**Comment by MoOx** [comment]
Perso tout me vas tant que c'est simple et rapide à mettre en place (vu l'état de la master).
Ne pas viser trop loin dessuite non plus, qu'on itère au plus court :)
Si on peut à terme rester sur du static (cache suprême) c'est bonus.

**Comment by MoOx** [comment]
Mon script est quasi fini pour les conversions
Tant qu'à y être on peut réorganiser les champs

Je propose (sans trop de raison)

```yaml
---
type: post
comments: true
date: 2014-10-27
route: post/js/flux-qu-est-ce-que-c-est
title: Flux, qu'est-ce que c'est ?
tags:
  - javascript
  - reactjs
  - flux
authors:
  - bloodyowl
---
```

Notez que je vois un champ `type` existant. On le garde pour le layout ?
Comment tu comptes gérer les pages "statiques" @bloodyowl ?
Ca serait bien d'avoir aussi des .md avec un truc style "type: page" (et le type sert à choper un layout qui va bien).
Je pense aussi que la route pourra être automatique mais on pourra voir en 2 temps pour la virer s'il la faut là en l'état.

**Comment by bloodyowl** [comment]
le `type` est pas nécessaire, la présence dans `posts` sera suffisante pour définir ça. pour les autres pages ce sera des layouts particuliers.

pour `comments` tout bien réfléchi, on peut mettre `true` par défaut et seulement ajouter `false` dans le cas où on souhaite les fermer.

**Comment by MoOx** [comment]
ok pour les comments.
Pour les "autres" pages, on peut se basser sur le même système de md ?

**Comment by bloodyowl** [comment]
README & comment participer en soi ce sont des posts non-listés, donc wai on utilise le même système, à voir si on les met pas ailleurs que posts/

**Comment by MoOx** [comment]
Closing for #361
